title: Curioler Research
description: Evidence-based research summaries for caregivers of autistic children.
baseurl: "/curioler-research"
url: "https://curioler-org.github.io"

collections:
  summaries:
    output: true
    permalink: /summaries/:name/
  myth_checks:
    output: true
    permalink: /myth-check/:name/
  studies:
    output: true
    permalink: /studies/:name/

defaults:
  - scope:
      path: ""
      type: summaries
    values:
      layout: summary
  - scope:
      path: ""
      type: myth_checks
    values:
      layout: myth_check
  - scope:
      path: ""
      type: studies
    values:
      layout: study

markdown: kramdown
plugins:
  - jekyll-feed
